# Generated by Django 4.2 on 2025-08-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customerpromotion_april_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='created_at',
            field=models.TextField(blank=True, null=True),
        ),
    ]
