# Generated by Django 4.2 on 2025-07-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=50)),
                ('metal_type', models.CharField(max_length=50)),
                ('karat', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stone_type', models.CharField(blank=True, max_length=50, null=True)),
                ('subcategory', models.CharField(max_length=100)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory_quantity', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('tags', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
