# Generated by Django 4.2 on 2025-08-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpromotion_april',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerpromotion_may',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
