# Generated by Django 4.2 on 2025-07-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_prompt_footer_prompt_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='header',
        ),
        migrations.AddField(
            model_name='prompt',
            name='type',
            field=models.TextField(default='Header', max_length=100),
        ),
    ]
