# Generated by Django 4.2 on 2025-07-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_promotion_june'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='promotion_june',
            table='customer_Promotion_June',
        ),
    ]
