# Generated by Django 4.2 on 2025-07-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_promotion_june_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion_june',
            name='price',
        ),
    ]
