# Generated by Django 4.2 on 2025-07-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customerpromotionjune_delete_promotion_june'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerpromotionjune',
            options={},
        ),
    ]
