# Generated by Django 4.2 on 2025-07-31 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customerpromotionapril_customerpromotionmay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerPromotionJune',
        ),
    ]
