# Generated by Django 4.2 on 2025-07-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_customerpromotionjune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpromotionjune',
            name='item_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerpromotionjune',
            name='product_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerpromotionjune',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerpromotionjune',
            name='varient_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
