# Generated by Django 4.2 on 2025-07-31 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_customerpromotionapril_customerpromotionjune_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerPromotionApril',
        ),
        migrations.DeleteModel(
            name='CustomerPromotionJune',
        ),
        migrations.DeleteModel(
            name='CustomerPromotionMay',
        ),
    ]
