# Generated by Django 4.2 on 2025-07-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_customerpromotion_may'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPromotion_April',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('item_id', models.CharField(max_length=255)),
                ('product_id', models.BigIntegerField()),
                ('variant_id', models.BigIntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conv_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('conv_value_per_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('impressions', models.IntegerField(default=0)),
                ('ctr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('conversions', models.IntegerField(default=0)),
                ('cost_per_conv', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('conv_value_per_click', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('value_per_conv', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('conv_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('all_conv', models.IntegerField(default=0)),
                ('all_conv_value_per_click', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('all_conv_value_per_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_per_all_conv', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('value_per_all_conv', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('all_conv_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('all_conv_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('units_sold', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('avg_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('orders', models.IntegerField(default=0)),
                ('avg_basket_size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_of_goods_sold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lead_units_sold', models.IntegerField(default=0)),
                ('cross_sell_units_sold', models.IntegerField(default=0)),
                ('lead_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cross_sell_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cross_device_conv', models.IntegerField(default=0)),
                ('cross_device_conv_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('category_1st_level', models.CharField(blank=True, max_length=255, null=True)),
                ('category_5th_level', models.CharField(blank=True, max_length=255, null=True)),
                ('category_2nd_level', models.CharField(blank=True, max_length=255, null=True)),
                ('category_3rd_level', models.CharField(blank=True, max_length=255, null=True)),
                ('category_4th_level', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type_1st_level', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'customer_promotion_april',
            },
        ),
    ]
