# Generated by Django 4.2 on 2025-08-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_customerpromotion_april'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
