# Generated by Django 4.2 on 2025-08-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_productvariant_created_at_productvariant_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='updated_at',
        ),
    ]
