# Generated by Django 4.2 on 2025-08-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_productvariant_created_at_productvariant_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerpromotion_april',
            old_name='variant_id',
            new_name='varient_id',
        ),
        migrations.RenameField(
            model_name='customerpromotion_may',
            old_name='variant_id',
            new_name='varient_id',
        ),
        migrations.RenameField(
            model_name='customerpromotionjune',
            old_name='varientid',
            new_name='varient_id',
        ),
    ]
