# Generated by Django 4.2 on 2025-08-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_rename_variant_id_customerpromotion_april_varient_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerpromotionjune',
            old_name='itemid',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='customerpromotionjune',
            old_name='productid',
            new_name='product_id',
        ),
    ]
