# Generated by Django 4.2 on 2025-08-01 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_rename_itemid_customerpromotionjune_item_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerpromotion_april',
            old_name='varient_id',
            new_name='variant_id',
        ),
        migrations.RenameField(
            model_name='customerpromotion_may',
            old_name='varient_id',
            new_name='variant_id',
        ),
        migrations.RenameField(
            model_name='customerpromotionjune',
            old_name='varient_id',
            new_name='variant_id',
        ),
    ]
