# Generated by Django 4.2 on 2025-08-02 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_rename_varient_id_customerpromotion_april_variant_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerPromotionJune',
            new_name='CustomerPromotion_June',
        ),
        migrations.RenameField(
            model_name='customerpromotion_june',
            old_name='impr',
            new_name='impressions',
        ),
    ]
